# Generated by Django 5.1.5 on 2026-06-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Bu sorunun yayınlanacağı tarih', unique=True, verbose_name='Tarih')),
                ('title', models.CharField(help_text='Örn: Zihin Açan Soru #42', max_length=200, verbose_name='Başlık')),
                ('question_text', models.TextField(blank=True, help_text='Metin tabanlı soru (resim yoksa)', verbose_name='Soru Metni')),
                ('question_image', models.ImageField(blank=True, help_text='Soru resmi (metin yoksa)', null=True, upload_to='daily_questions/%Y/%m/', verbose_name='Soru Görseli')),
                ('solution_url', models.URLField(blank=True, help_text='Instagram Reels çözüm videosu linki', verbose_name='Çözüm Linki')),
                ('difficulty', models.CharField(choices=[('kolay', 'Kolay'), ('orta', 'Orta'), ('zor', 'Zor')], default='orta', max_length=20, verbose_name='Zorluk')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Günün Sorusu',
                'verbose_name_plural': 'Günün Soruları',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Örn: Temel Matematik Teşhis Testi', max_length=200, verbose_name='Test Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('questions', models.JSONField(default=list, help_text="JSON formatında soru dizisi. Docstring'deki örneğe bakın.", verbose_name='Sorular (JSON)')),
                ('target_exam', models.CharField(choices=[('yks', 'YKS'), ('lgs', 'LGS'), ('genel', 'Genel')], default='genel', max_length=50, verbose_name='Hedef Sınav')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Teşhis Testi',
                'verbose_name_plural': 'Teşhis Testleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: YKS, LGS, MSÜ', max_length=100, verbose_name='Sınav Adı')),
                ('exam_date', models.DateTimeField(verbose_name='Sınav Tarihi ve Saati')),
                ('description', models.TextField(blank=True, help_text='Sınav hakkında kısa bilgi (opsiyonel)', verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Sınav Tarihi',
                'verbose_name_plural': 'Sınav Tarihleri',
                'ordering': ['exam_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='Öğrenci Adı')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('contact_source', models.CharField(choices=[('whatsapp_button', 'WhatsApp Butonu'), ('diagnostic_test', 'Teşhis Testi Sonucu'), ('free_session', 'Ücretsiz Seans Talebi'), ('other', 'Diğer')], default='other', max_length=30, verbose_name='İletişim Kaynağı')),
                ('weak_topics', models.JSONField(blank=True, default=list, help_text='Teşhis testinden gelen zayıf konular listesi', null=True, verbose_name='Eksik Konular')),
                ('diagnostic_score', models.IntegerField(blank=True, help_text='Teşhis testinden alınan puan (0-100)', null=True, verbose_name='Teşhis Puanı')),
                ('notes', models.TextField(blank=True, help_text='Öğrenci hakkında ek notlar', verbose_name='Notlar')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='İletişime geçildi mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Potansiyel Öğrenci',
                'verbose_name_plural': 'Potansiyel Öğrenciler',
                'ordering': ['-created_at'],
            },
        ),
    ]
