# Generated by Django 5.1.5 on 2026-06-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Duyuru Başlığı')),
                ('content', models.TextField(verbose_name='Duyuru İçeriği')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/%Y/%m/', verbose_name='Duyuru Görseli')),
                ('link_url', models.URLField(blank=True, help_text='Duyuruya tıklanınca açılacak link (opsiyonel)', verbose_name='Yönlendirme Linki')),
                ('is_pinned', models.BooleanField(default=False, help_text='Sabitlenmiş duyurular her zaman en üstte gösterilir', verbose_name='Sabitlenmiş mi?')),
                ('start_date', models.DateTimeField(help_text='Duyurunun gösterilmeye başlayacağı tarih', verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, help_text='Boş bırakılırsa süresiz gösterilir', null=True, verbose_name='Bitiş Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-is_pinned', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(default='Matematik Öğretmeni', max_length=100, verbose_name='Öğretmen Adı')),
                ('teacher_title', models.CharField(blank=True, help_text='Örn: Matematik Öğretmeni & Eğitim Danışmanı', max_length=200, verbose_name='Unvan / Başlık')),
                ('teacher_bio', models.TextField(blank=True, help_text='Destek sekmesinde gösterilecek öğretmen biyografisi', verbose_name='Özgeçmiş')),
                ('teacher_photo', models.ImageField(blank=True, null=True, upload_to='teacher/', verbose_name='Profil Fotoğrafı')),
                ('whatsapp_url', models.URLField(blank=True, help_text='Örn: https://wa.me/905XXXXXXXXX', verbose_name='WhatsApp Linki')),
                ('instagram_url', models.URLField(blank=True, help_text='Örn: https://instagram.com/kullaniciadi', verbose_name='Instagram Linki')),
                ('calendly_url', models.URLField(blank=True, help_text='Ücretsiz tanışma seansı için randevu linki', verbose_name='Calendly Linki')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube Linki')),
                ('website_url', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('cta_text', models.CharField(default='Hala kafan mı karışık? Ücretsiz Tanışma Seansı Ayarla', max_length=200, verbose_name='CTA Buton Metni')),
                ('cta_subtitle', models.CharField(blank=True, default='İlk görüşme tamamen ücretsiz!', max_length=200, verbose_name='CTA Alt Metni')),
                ('app_name', models.CharField(default='Porsuk: Sınav Koçu', max_length=100, verbose_name='Uygulama Adı')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Aktif edilirse uygulama bakım mesajı gösterir', verbose_name='Bakım Modu')),
                ('maintenance_message', models.TextField(blank=True, default='Uygulama şu anda bakımdadır. Kısa süre içinde geri döneceğiz!', verbose_name='Bakım Mesajı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Uygulama Ayarları',
                'verbose_name_plural': 'Uygulama Ayarları',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='ExponentPushToken[xxxx] formatında', max_length=255, unique=True, verbose_name='Expo Push Token')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='Cihaz Adı')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=20, verbose_name='Platform')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Cihaz Token',
                'verbose_name_plural': "Cihaz Token'ları",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormulaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('temel', 'Temel Matematik'), ('cebir', 'Cebir'), ('geometri', 'Geometri'), ('analiz', 'Analiz'), ('sayilar', 'Sayılar Teorisi'), ('olasilik', 'Olasılık & İstatistik'), ('trigonometri', 'Trigonometri'), ('diger', 'Diğer')], max_length=30, verbose_name='Konu')),
                ('title', models.CharField(help_text='Örn: Pisagor Teoremi, İkinci Dereceden Denklem Çözüm Formülü', max_length=200, verbose_name='Formül Başlığı')),
                ('formula_text', models.TextField(help_text='LaTeX veya düz metin formatında formül. Örn: a² + b² = c²', verbose_name='Formül Metni')),
                ('explanation', models.TextField(blank=True, help_text='Formülün ne zaman ve nasıl kullanıldığına dair kısa açıklama', verbose_name='Açıklama')),
                ('formula_image', models.ImageField(blank=True, help_text='Formülün görsel hali (opsiyonel)', null=True, upload_to='formulas/%Y/%m/', verbose_name='Formül Görseli')),
                ('order', models.IntegerField(default=0, help_text='Küçük sayılar önce gösterilir', verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Formül Kartı',
                'verbose_name_plural': 'Formül Kartları',
                'ordering': ['topic', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='Motivasyon sözü metni', verbose_name='Söz')),
                ('author', models.CharField(blank=True, help_text="Sözün sahibi (boş bırakılırsa 'Anonim' gösterilir)", max_length=100, verbose_name='Söyleyen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Motivasyon Sözü',
                'verbose_name_plural': 'Motivasyon Sözleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Örn: Yeni soru eklendi! 🎯', max_length=200, verbose_name='Bildirim Başlığı')),
                ('body', models.TextField(help_text='Bildirim mesajının gövdesi', verbose_name='Bildirim İçeriği')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Bildirime tıklanınca uygulamaya gönderilecek veri. Örn: {"screen": "daily_question"}', null=True, verbose_name='Ek Veri (JSON)')),
                ('send_at', models.DateTimeField(blank=True, help_text='Boş bırakılırsa hemen gönderilir', null=True, verbose_name='Gönderim Zamanı')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Gönderildi mi?')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Zamanı')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Gönderilen Cihaz Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
